using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.Customers.Credits.TopUps;

[JsonConverter(typeof(ModelConverter<TopUpCreateResponse, TopUpCreateResponseFromRaw>))]
public sealed record class TopUpCreateResponse : ModelBase
{
    public required string ID
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "id"); }
        init { ModelBase.Set(this._rawData, "id", value); }
    }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "amount"); }
        init { ModelBase.Set(this._rawData, "amount", value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "currency"); }
        init { ModelBase.Set(this._rawData, "currency", value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpInvoiceSettings InvoiceSettings
    {
        get
        {
            return ModelBase.GetNotNullClass<TopUpInvoiceSettings>(
                this.RawData,
                "invoice_settings"
            );
        }
        init { ModelBase.Set(this._rawData, "invoice_settings", value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "per_unit_cost_basis"); }
        init { ModelBase.Set(this._rawData, "per_unit_cost_basis", value); }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "threshold"); }
        init { ModelBase.Set(this._rawData, "threshold", value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get { return ModelBase.GetNullableStruct<long>(this.RawData, "expires_after"); }
        init { ModelBase.Set(this._rawData, "expires_after", value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public ApiEnum<string, TopUpCreateResponseExpiresAfterUnit>? ExpiresAfterUnit
    {
        get
        {
            return ModelBase.GetNullableClass<ApiEnum<string, TopUpCreateResponseExpiresAfterUnit>>(
                this.RawData,
                "expires_after_unit"
            );
        }
        init { ModelBase.Set(this._rawData, "expires_after_unit", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Amount;
        _ = this.Currency;
        this.InvoiceSettings.Validate();
        _ = this.PerUnitCostBasis;
        _ = this.Threshold;
        _ = this.ExpiresAfter;
        this.ExpiresAfterUnit?.Validate();
    }

    public TopUpCreateResponse() { }

    public TopUpCreateResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpCreateResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="TopUpCreateResponseFromRaw.FromRawUnchecked"/>
    public static TopUpCreateResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class TopUpCreateResponseFromRaw : IFromRaw<TopUpCreateResponse>
{
    /// <inheritdoc/>
    public TopUpCreateResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        TopUpCreateResponse.FromRawUnchecked(rawData);
}

/// <summary>
/// The unit of expires_after.
/// </summary>
[JsonConverter(typeof(TopUpCreateResponseExpiresAfterUnitConverter))]
public enum TopUpCreateResponseExpiresAfterUnit
{
    Day,
    Month,
}

sealed class TopUpCreateResponseExpiresAfterUnitConverter
    : JsonConverter<TopUpCreateResponseExpiresAfterUnit>
{
    public override TopUpCreateResponseExpiresAfterUnit Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "day" => TopUpCreateResponseExpiresAfterUnit.Day,
            "month" => TopUpCreateResponseExpiresAfterUnit.Month,
            _ => (TopUpCreateResponseExpiresAfterUnit)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        TopUpCreateResponseExpiresAfterUnit value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                TopUpCreateResponseExpiresAfterUnit.Day => "day",
                TopUpCreateResponseExpiresAfterUnit.Month => "month",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
