using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.Customers.Credits.TopUps;

[JsonConverter(typeof(JsonModelConverter<TopUpListResponse, TopUpListResponseFromRaw>))]
public sealed record class TopUpListResponse : JsonModel
{
    public required string ID
    {
        get { return this._rawData.GetNotNullClass<string>("id"); }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get { return this._rawData.GetNotNullClass<string>("amount"); }
        init { this._rawData.Set("amount", value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get { return this._rawData.GetNotNullClass<string>("currency"); }
        init { this._rawData.Set("currency", value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpInvoiceSettings InvoiceSettings
    {
        get { return this._rawData.GetNotNullClass<TopUpInvoiceSettings>("invoice_settings"); }
        init { this._rawData.Set("invoice_settings", value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get { return this._rawData.GetNotNullClass<string>("per_unit_cost_basis"); }
        init { this._rawData.Set("per_unit_cost_basis", value); }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get { return this._rawData.GetNotNullClass<string>("threshold"); }
        init { this._rawData.Set("threshold", value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get { return this._rawData.GetNullableStruct<long>("expires_after"); }
        init { this._rawData.Set("expires_after", value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public ApiEnum<string, TopUpListResponseExpiresAfterUnit>? ExpiresAfterUnit
    {
        get
        {
            return this._rawData.GetNullableClass<
                ApiEnum<string, TopUpListResponseExpiresAfterUnit>
            >("expires_after_unit");
        }
        init { this._rawData.Set("expires_after_unit", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Amount;
        _ = this.Currency;
        this.InvoiceSettings.Validate();
        _ = this.PerUnitCostBasis;
        _ = this.Threshold;
        _ = this.ExpiresAfter;
        this.ExpiresAfterUnit?.Validate();
    }

    public TopUpListResponse() { }

    public TopUpListResponse(TopUpListResponse topUpListResponse)
        : base(topUpListResponse) { }

    public TopUpListResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpListResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="TopUpListResponseFromRaw.FromRawUnchecked"/>
    public static TopUpListResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class TopUpListResponseFromRaw : IFromRawJson<TopUpListResponse>
{
    /// <inheritdoc/>
    public TopUpListResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        TopUpListResponse.FromRawUnchecked(rawData);
}

/// <summary>
/// The unit of expires_after.
/// </summary>
[JsonConverter(typeof(TopUpListResponseExpiresAfterUnitConverter))]
public enum TopUpListResponseExpiresAfterUnit
{
    Day,
    Month,
}

sealed class TopUpListResponseExpiresAfterUnitConverter
    : JsonConverter<TopUpListResponseExpiresAfterUnit>
{
    public override TopUpListResponseExpiresAfterUnit Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "day" => TopUpListResponseExpiresAfterUnit.Day,
            "month" => TopUpListResponseExpiresAfterUnit.Month,
            _ => (TopUpListResponseExpiresAfterUnit)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        TopUpListResponseExpiresAfterUnit value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                TopUpListResponseExpiresAfterUnit.Day => "day",
                TopUpListResponseExpiresAfterUnit.Month => "month",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
