using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.Customers.Credits.TopUps;

[JsonConverter(
    typeof(ModelConverter<
        TopUpListByExternalIDPageResponse,
        TopUpListByExternalIDPageResponseFromRaw
    >)
)]
public sealed record class TopUpListByExternalIDPageResponse : ModelBase
{
    public required IReadOnlyList<global::Orb.Models.Customers.Credits.TopUps.DataModel> Data
    {
        get
        {
            return ModelBase.GetNotNullClass<
                List<global::Orb.Models.Customers.Credits.TopUps.DataModel>
            >(this.RawData, "data");
        }
        init { ModelBase.Set(this._rawData, "data", value); }
    }

    public required PaginationMetadata PaginationMetadata
    {
        get
        {
            return ModelBase.GetNotNullClass<PaginationMetadata>(
                this.RawData,
                "pagination_metadata"
            );
        }
        init { ModelBase.Set(this._rawData, "pagination_metadata", value); }
    }

    public override void Validate()
    {
        foreach (var item in this.Data)
        {
            item.Validate();
        }
        this.PaginationMetadata.Validate();
    }

    public TopUpListByExternalIDPageResponse() { }

    public TopUpListByExternalIDPageResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpListByExternalIDPageResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    public static TopUpListByExternalIDPageResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class TopUpListByExternalIDPageResponseFromRaw : IFromRaw<TopUpListByExternalIDPageResponse>
{
    public TopUpListByExternalIDPageResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => TopUpListByExternalIDPageResponse.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(ModelConverter<
        global::Orb.Models.Customers.Credits.TopUps.DataModel,
        global::Orb.Models.Customers.Credits.TopUps.DataModelFromRaw
    >)
)]
public sealed record class DataModel : ModelBase
{
    public required string ID
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "id"); }
        init { ModelBase.Set(this._rawData, "id", value); }
    }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "amount"); }
        init { ModelBase.Set(this._rawData, "amount", value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "currency"); }
        init { ModelBase.Set(this._rawData, "currency", value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpInvoiceSettings InvoiceSettings
    {
        get
        {
            return ModelBase.GetNotNullClass<TopUpInvoiceSettings>(
                this.RawData,
                "invoice_settings"
            );
        }
        init { ModelBase.Set(this._rawData, "invoice_settings", value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "per_unit_cost_basis"); }
        init { ModelBase.Set(this._rawData, "per_unit_cost_basis", value); }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "threshold"); }
        init { ModelBase.Set(this._rawData, "threshold", value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get { return ModelBase.GetNullableStruct<long>(this.RawData, "expires_after"); }
        init { ModelBase.Set(this._rawData, "expires_after", value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public ApiEnum<string, DataModelExpiresAfterUnit>? ExpiresAfterUnit
    {
        get
        {
            return ModelBase.GetNullableClass<ApiEnum<string, DataModelExpiresAfterUnit>>(
                this.RawData,
                "expires_after_unit"
            );
        }
        init { ModelBase.Set(this._rawData, "expires_after_unit", value); }
    }

    public override void Validate()
    {
        _ = this.ID;
        _ = this.Amount;
        _ = this.Currency;
        this.InvoiceSettings.Validate();
        _ = this.PerUnitCostBasis;
        _ = this.Threshold;
        _ = this.ExpiresAfter;
        this.ExpiresAfterUnit?.Validate();
    }

    public DataModel() { }

    public DataModel(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    DataModel(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    public static global::Orb.Models.Customers.Credits.TopUps.DataModel FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class DataModelFromRaw : IFromRaw<global::Orb.Models.Customers.Credits.TopUps.DataModel>
{
    public global::Orb.Models.Customers.Credits.TopUps.DataModel FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => global::Orb.Models.Customers.Credits.TopUps.DataModel.FromRawUnchecked(rawData);
}

/// <summary>
/// The unit of expires_after.
/// </summary>
[JsonConverter(typeof(DataModelExpiresAfterUnitConverter))]
public enum DataModelExpiresAfterUnit
{
    Day,
    Month,
}

sealed class DataModelExpiresAfterUnitConverter : JsonConverter<DataModelExpiresAfterUnit>
{
    public override DataModelExpiresAfterUnit Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "day" => DataModelExpiresAfterUnit.Day,
            "month" => DataModelExpiresAfterUnit.Month,
            _ => (DataModelExpiresAfterUnit)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        DataModelExpiresAfterUnit value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                DataModelExpiresAfterUnit.Day => "day",
                DataModelExpiresAfterUnit.Month => "month",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
