using CodeAnalysis = System.Diagnostics.CodeAnalysis;
using Generic = System.Collections.Generic;
using Json = System.Text.Json;
using Orb = Orb;
using Serialization = System.Text.Json.Serialization;
using System = System;
using TopUpCreateByExternalIDResponseProperties = Orb.Models.Customers.Credits.TopUps.TopUpCreateByExternalIDResponseProperties;

namespace Orb.Models.Customers.Credits.TopUps;

[Serialization::JsonConverter(typeof(Orb::ModelConverter<TopUpCreateByExternalIDResponse>))]
public sealed record class TopUpCreateByExternalIDResponse
    : Orb::ModelBase,
        Orb::IFromRaw<TopUpCreateByExternalIDResponse>
{
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("id", "Missing required argument");

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("id");
        }
        set { this.Properties["id"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get
        {
            if (!this.Properties.TryGetValue("amount", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "amount",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("amount");
        }
        set { this.Properties["amount"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get
        {
            if (!this.Properties.TryGetValue("currency", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "currency",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("currency");
        }
        set { this.Properties["currency"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpInvoiceSettings InvoiceSettings
    {
        get
        {
            if (!this.Properties.TryGetValue("invoice_settings", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "invoice_settings",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<TopUpInvoiceSettings>(element)
                ?? throw new System::ArgumentNullException("invoice_settings");
        }
        set
        {
            this.Properties["invoice_settings"] = Json::JsonSerializer.SerializeToElement(value);
        }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get
        {
            if (!this.Properties.TryGetValue("per_unit_cost_basis", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "per_unit_cost_basis",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("per_unit_cost_basis");
        }
        set
        {
            this.Properties["per_unit_cost_basis"] = Json::JsonSerializer.SerializeToElement(value);
        }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get
        {
            if (!this.Properties.TryGetValue("threshold", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "threshold",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("threshold");
        }
        set { this.Properties["threshold"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get
        {
            if (!this.Properties.TryGetValue("expires_after", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<long?>(element);
        }
        set { this.Properties["expires_after"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public TopUpCreateByExternalIDResponseProperties::ExpiresAfterUnit? ExpiresAfterUnit
    {
        get
        {
            if (!this.Properties.TryGetValue("expires_after_unit", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<TopUpCreateByExternalIDResponseProperties::ExpiresAfterUnit?>(
                element
            );
        }
        set
        {
            this.Properties["expires_after_unit"] = Json::JsonSerializer.SerializeToElement(value);
        }
    }

    public override void Validate()
    {
        _ = this.ID;
        _ = this.Amount;
        _ = this.Currency;
        this.InvoiceSettings.Validate();
        _ = this.PerUnitCostBasis;
        _ = this.Threshold;
        _ = this.ExpiresAfter;
        this.ExpiresAfterUnit?.Validate();
    }

    public TopUpCreateByExternalIDResponse() { }

#pragma warning disable CS8618
    [CodeAnalysis::SetsRequiredMembers]
    TopUpCreateByExternalIDResponse(Generic::Dictionary<string, Json::JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static TopUpCreateByExternalIDResponse FromRawUnchecked(
        Generic::Dictionary<string, Json::JsonElement> properties
    )
    {
        return new(properties);
    }
}
