using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.Customers.Credits.TopUps;

/// <summary>
/// This endpoint allows you to create a new top-up for a specified customer's balance.
/// While this top-up is active, the customer's balance will added in increments
/// of the specified amount whenever the balance reaches the specified threshold.
///
/// <para>If a top-up already exists for this customer in the same currency, the existing
/// top-up will be replaced.</para>
/// </summary>
public sealed record class TopUpCreateByExternalIDParams : ParamsBase
{
    readonly JsonDictionary _rawBodyData = new();
    public IReadOnlyDictionary<string, JsonElement> RawBodyData
    {
        get { return this._rawBodyData.Freeze(); }
    }

    public string? ExternalCustomerID { get; init; }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("amount");
        }
        init { this._rawBodyData.Set("amount", value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("currency");
        }
        init { this._rawBodyData.Set("currency", value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpCreateByExternalIDParamsInvoiceSettings InvoiceSettings
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<TopUpCreateByExternalIDParamsInvoiceSettings>(
                "invoice_settings"
            );
        }
        init { this._rawBodyData.Set("invoice_settings", value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("per_unit_cost_basis");
        }
        init { this._rawBodyData.Set("per_unit_cost_basis", value); }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>("threshold");
        }
        init { this._rawBodyData.Set("threshold", value); }
    }

    /// <summary>
    /// The date from which the top-up is active. If unspecified, the top-up is active
    /// immediately.             This should not be more than 10 days in the past.
    /// </summary>
    public System::DateTimeOffset? ActiveFrom
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<System::DateTimeOffset>("active_from");
        }
        init { this._rawBodyData.Set("active_from", value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<long>("expires_after");
        }
        init { this._rawBodyData.Set("expires_after", value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public ApiEnum<string, TopUpCreateByExternalIDParamsExpiresAfterUnit>? ExpiresAfterUnit
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<
                ApiEnum<string, TopUpCreateByExternalIDParamsExpiresAfterUnit>
            >("expires_after_unit");
        }
        init { this._rawBodyData.Set("expires_after_unit", value); }
    }

    public TopUpCreateByExternalIDParams() { }

    public TopUpCreateByExternalIDParams(
        TopUpCreateByExternalIDParams topUpCreateByExternalIDParams
    )
        : base(topUpCreateByExternalIDParams)
    {
        this.ExternalCustomerID = topUpCreateByExternalIDParams.ExternalCustomerID;

        this._rawBodyData = new(topUpCreateByExternalIDParams._rawBodyData);
    }

    public TopUpCreateByExternalIDParams(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpCreateByExternalIDParams(
        FrozenDictionary<string, JsonElement> rawHeaderData,
        FrozenDictionary<string, JsonElement> rawQueryData,
        FrozenDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="IFromRawJson.FromRawUnchecked"/>
    public static TopUpCreateByExternalIDParams FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        return new(
            FrozenDictionary.ToFrozenDictionary(rawHeaderData),
            FrozenDictionary.ToFrozenDictionary(rawQueryData),
            FrozenDictionary.ToFrozenDictionary(rawBodyData)
        );
    }

    public override System::Uri Url(ClientOptions options)
    {
        return new System::UriBuilder(
            options.BaseUrl.ToString().TrimEnd('/')
                + string.Format(
                    "/customers/external_customer_id/{0}/credits/top_ups",
                    this.ExternalCustomerID
                )
        )
        {
            Query = this.QueryString(options),
        }.Uri;
    }

    internal override HttpContent? BodyContent()
    {
        return new StringContent(
            JsonSerializer.Serialize(this.RawBodyData, ModelBase.SerializerOptions),
            Encoding.UTF8,
            "application/json"
        );
    }

    internal override void AddHeadersToRequest(HttpRequestMessage request, ClientOptions options)
    {
        ParamsBase.AddDefaultHeaders(request, options);
        foreach (var item in this.RawHeaderData)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }
}

/// <summary>
/// Settings for invoices generated by triggered top-ups.
/// </summary>
[JsonConverter(
    typeof(JsonModelConverter<
        TopUpCreateByExternalIDParamsInvoiceSettings,
        TopUpCreateByExternalIDParamsInvoiceSettingsFromRaw
    >)
)]
public sealed record class TopUpCreateByExternalIDParamsInvoiceSettings : JsonModel
{
    /// <summary>
    /// Whether the credits purchase invoice should auto collect with the customer's
    /// saved payment method.
    /// </summary>
    public required bool AutoCollection
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<bool>("auto_collection");
        }
        init { this._rawData.Set("auto_collection", value); }
    }

    /// <summary>
    /// The net terms determines the difference between the invoice date and the
    /// issue date for the invoice. If you intend the invoice to be due on issue,
    /// set this to 0.
    /// </summary>
    public required long NetTerms
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<long>("net_terms");
        }
        init { this._rawData.Set("net_terms", value); }
    }

    /// <summary>
    /// An optional memo to display on the invoice.
    /// </summary>
    public string? Memo
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("memo");
        }
        init { this._rawData.Set("memo", value); }
    }

    /// <summary>
    /// When true, credit blocks created by this top-up will require that the corresponding
    /// invoice is paid before they are drawn down from. If any topup block is pending
    /// payment, further automatic top-ups will be paused until the invoice is paid
    /// or voided.
    /// </summary>
    public bool? RequireSuccessfulPayment
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("require_successful_payment");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("require_successful_payment", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.AutoCollection;
        _ = this.NetTerms;
        _ = this.Memo;
        _ = this.RequireSuccessfulPayment;
    }

    public TopUpCreateByExternalIDParamsInvoiceSettings() { }

    public TopUpCreateByExternalIDParamsInvoiceSettings(
        TopUpCreateByExternalIDParamsInvoiceSettings topUpCreateByExternalIDParamsInvoiceSettings
    )
        : base(topUpCreateByExternalIDParamsInvoiceSettings) { }

    public TopUpCreateByExternalIDParamsInvoiceSettings(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpCreateByExternalIDParamsInvoiceSettings(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="TopUpCreateByExternalIDParamsInvoiceSettingsFromRaw.FromRawUnchecked"/>
    public static TopUpCreateByExternalIDParamsInvoiceSettings FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class TopUpCreateByExternalIDParamsInvoiceSettingsFromRaw
    : IFromRawJson<TopUpCreateByExternalIDParamsInvoiceSettings>
{
    /// <inheritdoc/>
    public TopUpCreateByExternalIDParamsInvoiceSettings FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => TopUpCreateByExternalIDParamsInvoiceSettings.FromRawUnchecked(rawData);
}

/// <summary>
/// The unit of expires_after.
/// </summary>
[JsonConverter(typeof(TopUpCreateByExternalIDParamsExpiresAfterUnitConverter))]
public enum TopUpCreateByExternalIDParamsExpiresAfterUnit
{
    Day,
    Month,
}

sealed class TopUpCreateByExternalIDParamsExpiresAfterUnitConverter
    : JsonConverter<TopUpCreateByExternalIDParamsExpiresAfterUnit>
{
    public override TopUpCreateByExternalIDParamsExpiresAfterUnit Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "day" => TopUpCreateByExternalIDParamsExpiresAfterUnit.Day,
            "month" => TopUpCreateByExternalIDParamsExpiresAfterUnit.Month,
            _ => (TopUpCreateByExternalIDParamsExpiresAfterUnit)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        TopUpCreateByExternalIDParamsExpiresAfterUnit value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                TopUpCreateByExternalIDParamsExpiresAfterUnit.Day => "day",
                TopUpCreateByExternalIDParamsExpiresAfterUnit.Month => "month",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
