using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.Customers.Credits.TopUps;

[JsonConverter(typeof(JsonModelConverter<TopUpListPageResponse, TopUpListPageResponseFromRaw>))]
public sealed record class TopUpListPageResponse : JsonModel
{
    public required IReadOnlyList<global::Orb.Models.Customers.Credits.TopUps.Data> Data
    {
        get
        {
            return JsonModel.GetNotNullClass<
                List<global::Orb.Models.Customers.Credits.TopUps.Data>
            >(this.RawData, "data");
        }
        init { JsonModel.Set(this._rawData, "data", value); }
    }

    public required PaginationMetadata PaginationMetadata
    {
        get
        {
            return JsonModel.GetNotNullClass<PaginationMetadata>(
                this.RawData,
                "pagination_metadata"
            );
        }
        init { JsonModel.Set(this._rawData, "pagination_metadata", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        foreach (var item in this.Data)
        {
            item.Validate();
        }
        this.PaginationMetadata.Validate();
    }

    public TopUpListPageResponse() { }

    public TopUpListPageResponse(TopUpListPageResponse topUpListPageResponse)
        : base(topUpListPageResponse) { }

    public TopUpListPageResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    TopUpListPageResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="TopUpListPageResponseFromRaw.FromRawUnchecked"/>
    public static TopUpListPageResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class TopUpListPageResponseFromRaw : IFromRawJson<TopUpListPageResponse>
{
    /// <inheritdoc/>
    public TopUpListPageResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => TopUpListPageResponse.FromRawUnchecked(rawData);
}

[JsonConverter(
    typeof(JsonModelConverter<
        global::Orb.Models.Customers.Credits.TopUps.Data,
        global::Orb.Models.Customers.Credits.TopUps.DataFromRaw
    >)
)]
public sealed record class Data : JsonModel
{
    public required string ID
    {
        get { return JsonModel.GetNotNullClass<string>(this.RawData, "id"); }
        init { JsonModel.Set(this._rawData, "id", value); }
    }

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get { return JsonModel.GetNotNullClass<string>(this.RawData, "amount"); }
        init { JsonModel.Set(this._rawData, "amount", value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get { return JsonModel.GetNotNullClass<string>(this.RawData, "currency"); }
        init { JsonModel.Set(this._rawData, "currency", value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpInvoiceSettings InvoiceSettings
    {
        get
        {
            return JsonModel.GetNotNullClass<TopUpInvoiceSettings>(
                this.RawData,
                "invoice_settings"
            );
        }
        init { JsonModel.Set(this._rawData, "invoice_settings", value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get { return JsonModel.GetNotNullClass<string>(this.RawData, "per_unit_cost_basis"); }
        init { JsonModel.Set(this._rawData, "per_unit_cost_basis", value); }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get { return JsonModel.GetNotNullClass<string>(this.RawData, "threshold"); }
        init { JsonModel.Set(this._rawData, "threshold", value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get { return JsonModel.GetNullableStruct<long>(this.RawData, "expires_after"); }
        init { JsonModel.Set(this._rawData, "expires_after", value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public ApiEnum<string, DataExpiresAfterUnit>? ExpiresAfterUnit
    {
        get
        {
            return JsonModel.GetNullableClass<ApiEnum<string, DataExpiresAfterUnit>>(
                this.RawData,
                "expires_after_unit"
            );
        }
        init { JsonModel.Set(this._rawData, "expires_after_unit", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Amount;
        _ = this.Currency;
        this.InvoiceSettings.Validate();
        _ = this.PerUnitCostBasis;
        _ = this.Threshold;
        _ = this.ExpiresAfter;
        this.ExpiresAfterUnit?.Validate();
    }

    public Data() { }

    public Data(global::Orb.Models.Customers.Credits.TopUps.Data data)
        : base(data) { }

    public Data(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Data(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="global::Orb.Models.Customers.Credits.TopUps.DataFromRaw.FromRawUnchecked"/>
    public static global::Orb.Models.Customers.Credits.TopUps.Data FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class DataFromRaw : IFromRawJson<global::Orb.Models.Customers.Credits.TopUps.Data>
{
    /// <inheritdoc/>
    public global::Orb.Models.Customers.Credits.TopUps.Data FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => global::Orb.Models.Customers.Credits.TopUps.Data.FromRawUnchecked(rawData);
}

/// <summary>
/// The unit of expires_after.
/// </summary>
[JsonConverter(typeof(DataExpiresAfterUnitConverter))]
public enum DataExpiresAfterUnit
{
    Day,
    Month,
}

sealed class DataExpiresAfterUnitConverter : JsonConverter<DataExpiresAfterUnit>
{
    public override DataExpiresAfterUnit Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "day" => DataExpiresAfterUnit.Day,
            "month" => DataExpiresAfterUnit.Month,
            _ => (DataExpiresAfterUnit)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        DataExpiresAfterUnit value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                DataExpiresAfterUnit.Day => "day",
                DataExpiresAfterUnit.Month => "month",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
