using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using TopUpCreateParamsProperties = Orb.Models.Customers.Credits.TopUps.TopUpCreateParamsProperties;

namespace Orb.Models.Customers.Credits.TopUps;

/// <summary>
/// This endpoint allows you to create a new top-up for a specified customer's balance.
/// While this top-up is active, the customer's balance will added in increments of
/// the specified amount whenever the balance reaches the specified threshold.
///
/// If a top-up already exists for this customer in the same currency, the existing
/// top-up will be replaced.
/// </summary>
public sealed record class TopUpCreateParams : ParamsBase
{
    public Dictionary<string, JsonElement> BodyProperties { get; set; } = [];

    public required string CustomerID;

    /// <summary>
    /// The amount to increment when the threshold is reached.
    /// </summary>
    public required string Amount
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("amount", out JsonElement element))
                throw new ArgumentOutOfRangeException("amount", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("amount");
        }
        set { this.BodyProperties["amount"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The currency or custom pricing unit to use for this top-up. If this is a real-world
    /// currency, it must match the customer's invoicing currency.
    /// </summary>
    public required string Currency
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("currency", out JsonElement element))
                throw new ArgumentOutOfRangeException("currency", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("currency");
        }
        set { this.BodyProperties["currency"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Settings for invoices generated by triggered top-ups.
    /// </summary>
    public required TopUpCreateParamsProperties::InvoiceSettings InvoiceSettings
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("invoice_settings", out JsonElement element))
                throw new ArgumentOutOfRangeException(
                    "invoice_settings",
                    "Missing required argument"
                );

            return JsonSerializer.Deserialize<TopUpCreateParamsProperties::InvoiceSettings>(element)
                ?? throw new ArgumentNullException("invoice_settings");
        }
        set { this.BodyProperties["invoice_settings"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// How much, in the customer's currency, to charge for each unit.
    /// </summary>
    public required string PerUnitCostBasis
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("per_unit_cost_basis", out JsonElement element))
                throw new ArgumentOutOfRangeException(
                    "per_unit_cost_basis",
                    "Missing required argument"
                );

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("per_unit_cost_basis");
        }
        set
        {
            this.BodyProperties["per_unit_cost_basis"] = JsonSerializer.SerializeToElement(value);
        }
    }

    /// <summary>
    /// The threshold at which to trigger the top-up. If the balance is at or below
    /// this threshold, the top-up will be triggered.
    /// </summary>
    public required string Threshold
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("threshold", out JsonElement element))
                throw new ArgumentOutOfRangeException("threshold", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("threshold");
        }
        set { this.BodyProperties["threshold"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The date from which the top-up is active. If unspecified, the top-up is active
    /// immediately.             This should not be more than 10 days in the past.
    /// </summary>
    public DateTime? ActiveFrom
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("active_from", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<DateTime?>(element);
        }
        set { this.BodyProperties["active_from"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The number of days or months after which the top-up expires. If unspecified,
    /// it does not expire.
    /// </summary>
    public long? ExpiresAfter
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("expires_after", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<long?>(element);
        }
        set { this.BodyProperties["expires_after"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The unit of expires_after.
    /// </summary>
    public TopUpCreateParamsProperties::ExpiresAfterUnit? ExpiresAfterUnit
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("expires_after_unit", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<TopUpCreateParamsProperties::ExpiresAfterUnit?>(
                element
            );
        }
        set
        {
            this.BodyProperties["expires_after_unit"] = JsonSerializer.SerializeToElement(value);
        }
    }

    public override Uri Url(IOrbClient client)
    {
        return new UriBuilder(
            client.BaseUrl.ToString().TrimEnd('/')
                + string.Format("/customers/{0}/credits/top_ups", this.CustomerID)
        )
        {
            Query = this.QueryString(client),
        }.Uri;
    }

    public StringContent BodyContent()
    {
        return new(
            JsonSerializer.Serialize(this.BodyProperties),
            Encoding.UTF8,
            "application/json"
        );
    }

    public void AddHeadersToRequest(HttpRequestMessage request, IOrbClient client)
    {
        ParamsBase.AddDefaultHeaders(request, client);
        foreach (var item in this.HeaderProperties)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }
}
