using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Exceptions;
using System = System;

namespace Orb.Models.CustomerTaxIDProperties;

[JsonConverter(typeof(CountryConverter))]
public enum Country
{
    Ad,
    Ae,
    Al,
    Am,
    Ao,
    Ar,
    At,
    Au,
    Aw,
    Az,
    Ba,
    Bb,
    Bd,
    Be,
    Bf,
    Bg,
    Bh,
    Bj,
    Bo,
    Br,
    Bs,
    By,
    Ca,
    Cd,
    Ch,
    Cl,
    Cm,
    Cn,
    Co,
    Cr,
    Cv,
    De,
    Cy,
    Cz,
    Dk,
    Do,
    Ec,
    Ee,
    Eg,
    Es,
    Et,
    Eu,
    Fi,
    Fr,
    GB,
    Ge,
    Gn,
    Gr,
    Hk,
    Hr,
    Hu,
    ID,
    Ie,
    Il,
    In,
    Is,
    It,
    Jp,
    Ke,
    Kg,
    Kh,
    Kr,
    Kz,
    La,
    Li,
    Lt,
    Lu,
    Lv,
    Ma,
    Md,
    Me,
    Mk,
    Mr,
    Mt,
    Mx,
    My,
    Ng,
    Nl,
    No,
    Np,
    Nz,
    Om,
    Pe,
    Ph,
    Pl,
    Pt,
    Ro,
    Rs,
    Ru,
    Sa,
    Se,
    Sg,
    Si,
    Sk,
    Sn,
    Sr,
    Sv,
    Th,
    Tj,
    Tr,
    Tw,
    Tz,
    Ua,
    Ug,
    Us,
    Uy,
    Uz,
    Ve,
    Vn,
    Za,
    Zm,
    Zw,
}

sealed class CountryConverter : JsonConverter<Country>
{
    public override Country Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "AD" => Country.Ad,
            "AE" => Country.Ae,
            "AL" => Country.Al,
            "AM" => Country.Am,
            "AO" => Country.Ao,
            "AR" => Country.Ar,
            "AT" => Country.At,
            "AU" => Country.Au,
            "AW" => Country.Aw,
            "AZ" => Country.Az,
            "BA" => Country.Ba,
            "BB" => Country.Bb,
            "BD" => Country.Bd,
            "BE" => Country.Be,
            "BF" => Country.Bf,
            "BG" => Country.Bg,
            "BH" => Country.Bh,
            "BJ" => Country.Bj,
            "BO" => Country.Bo,
            "BR" => Country.Br,
            "BS" => Country.Bs,
            "BY" => Country.By,
            "CA" => Country.Ca,
            "CD" => Country.Cd,
            "CH" => Country.Ch,
            "CL" => Country.Cl,
            "CM" => Country.Cm,
            "CN" => Country.Cn,
            "CO" => Country.Co,
            "CR" => Country.Cr,
            "CV" => Country.Cv,
            "DE" => Country.De,
            "CY" => Country.Cy,
            "CZ" => Country.Cz,
            "DK" => Country.Dk,
            "DO" => Country.Do,
            "EC" => Country.Ec,
            "EE" => Country.Ee,
            "EG" => Country.Eg,
            "ES" => Country.Es,
            "ET" => Country.Et,
            "EU" => Country.Eu,
            "FI" => Country.Fi,
            "FR" => Country.Fr,
            "GB" => Country.GB,
            "GE" => Country.Ge,
            "GN" => Country.Gn,
            "GR" => Country.Gr,
            "HK" => Country.Hk,
            "HR" => Country.Hr,
            "HU" => Country.Hu,
            "ID" => Country.ID,
            "IE" => Country.Ie,
            "IL" => Country.Il,
            "IN" => Country.In,
            "IS" => Country.Is,
            "IT" => Country.It,
            "JP" => Country.Jp,
            "KE" => Country.Ke,
            "KG" => Country.Kg,
            "KH" => Country.Kh,
            "KR" => Country.Kr,
            "KZ" => Country.Kz,
            "LA" => Country.La,
            "LI" => Country.Li,
            "LT" => Country.Lt,
            "LU" => Country.Lu,
            "LV" => Country.Lv,
            "MA" => Country.Ma,
            "MD" => Country.Md,
            "ME" => Country.Me,
            "MK" => Country.Mk,
            "MR" => Country.Mr,
            "MT" => Country.Mt,
            "MX" => Country.Mx,
            "MY" => Country.My,
            "NG" => Country.Ng,
            "NL" => Country.Nl,
            "NO" => Country.No,
            "NP" => Country.Np,
            "NZ" => Country.Nz,
            "OM" => Country.Om,
            "PE" => Country.Pe,
            "PH" => Country.Ph,
            "PL" => Country.Pl,
            "PT" => Country.Pt,
            "RO" => Country.Ro,
            "RS" => Country.Rs,
            "RU" => Country.Ru,
            "SA" => Country.Sa,
            "SE" => Country.Se,
            "SG" => Country.Sg,
            "SI" => Country.Si,
            "SK" => Country.Sk,
            "SN" => Country.Sn,
            "SR" => Country.Sr,
            "SV" => Country.Sv,
            "TH" => Country.Th,
            "TJ" => Country.Tj,
            "TR" => Country.Tr,
            "TW" => Country.Tw,
            "TZ" => Country.Tz,
            "UA" => Country.Ua,
            "UG" => Country.Ug,
            "US" => Country.Us,
            "UY" => Country.Uy,
            "UZ" => Country.Uz,
            "VE" => Country.Ve,
            "VN" => Country.Vn,
            "ZA" => Country.Za,
            "ZM" => Country.Zm,
            "ZW" => Country.Zw,
            _ => (Country)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Country value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Country.Ad => "AD",
                Country.Ae => "AE",
                Country.Al => "AL",
                Country.Am => "AM",
                Country.Ao => "AO",
                Country.Ar => "AR",
                Country.At => "AT",
                Country.Au => "AU",
                Country.Aw => "AW",
                Country.Az => "AZ",
                Country.Ba => "BA",
                Country.Bb => "BB",
                Country.Bd => "BD",
                Country.Be => "BE",
                Country.Bf => "BF",
                Country.Bg => "BG",
                Country.Bh => "BH",
                Country.Bj => "BJ",
                Country.Bo => "BO",
                Country.Br => "BR",
                Country.Bs => "BS",
                Country.By => "BY",
                Country.Ca => "CA",
                Country.Cd => "CD",
                Country.Ch => "CH",
                Country.Cl => "CL",
                Country.Cm => "CM",
                Country.Cn => "CN",
                Country.Co => "CO",
                Country.Cr => "CR",
                Country.Cv => "CV",
                Country.De => "DE",
                Country.Cy => "CY",
                Country.Cz => "CZ",
                Country.Dk => "DK",
                Country.Do => "DO",
                Country.Ec => "EC",
                Country.Ee => "EE",
                Country.Eg => "EG",
                Country.Es => "ES",
                Country.Et => "ET",
                Country.Eu => "EU",
                Country.Fi => "FI",
                Country.Fr => "FR",
                Country.GB => "GB",
                Country.Ge => "GE",
                Country.Gn => "GN",
                Country.Gr => "GR",
                Country.Hk => "HK",
                Country.Hr => "HR",
                Country.Hu => "HU",
                Country.ID => "ID",
                Country.Ie => "IE",
                Country.Il => "IL",
                Country.In => "IN",
                Country.Is => "IS",
                Country.It => "IT",
                Country.Jp => "JP",
                Country.Ke => "KE",
                Country.Kg => "KG",
                Country.Kh => "KH",
                Country.Kr => "KR",
                Country.Kz => "KZ",
                Country.La => "LA",
                Country.Li => "LI",
                Country.Lt => "LT",
                Country.Lu => "LU",
                Country.Lv => "LV",
                Country.Ma => "MA",
                Country.Md => "MD",
                Country.Me => "ME",
                Country.Mk => "MK",
                Country.Mr => "MR",
                Country.Mt => "MT",
                Country.Mx => "MX",
                Country.My => "MY",
                Country.Ng => "NG",
                Country.Nl => "NL",
                Country.No => "NO",
                Country.Np => "NP",
                Country.Nz => "NZ",
                Country.Om => "OM",
                Country.Pe => "PE",
                Country.Ph => "PH",
                Country.Pl => "PL",
                Country.Pt => "PT",
                Country.Ro => "RO",
                Country.Rs => "RS",
                Country.Ru => "RU",
                Country.Sa => "SA",
                Country.Se => "SE",
                Country.Sg => "SG",
                Country.Si => "SI",
                Country.Sk => "SK",
                Country.Sn => "SN",
                Country.Sr => "SR",
                Country.Sv => "SV",
                Country.Th => "TH",
                Country.Tj => "TJ",
                Country.Tr => "TR",
                Country.Tw => "TW",
                Country.Tz => "TZ",
                Country.Ua => "UA",
                Country.Ug => "UG",
                Country.Us => "US",
                Country.Uy => "UY",
                Country.Uz => "UZ",
                Country.Ve => "VE",
                Country.Vn => "VN",
                Country.Za => "ZA",
                Country.Zm => "ZM",
                Country.Zw => "ZW",
                _ => throw new OrbInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
