using System.Text.Json;
using System.Text.Json.Serialization;
using System = System;

namespace Orb.Models.CustomerTaxIDProperties;

[JsonConverter(typeof(TypeConverter))]
public enum Type
{
    AdNrt,
    AeTrn,
    AlTin,
    AmTin,
    AoTin,
    ArCuit,
    EuVat,
    AuAbn,
    AuArn,
    AwTin,
    AzTin,
    BaTin,
    BbTin,
    BdBin,
    BfIfu,
    BgUic,
    BhVat,
    BjIfu,
    BoTin,
    BrCnpj,
    BrCpf,
    BsTin,
    ByTin,
    CaBn,
    CaGstHst,
    CaPstBc,
    CaPstMB,
    CaPstSk,
    CaQst,
    CdNif,
    ChUid,
    ChVat,
    ClTin,
    CmNiu,
    CnTin,
    CoNit,
    CrTin,
    CvNif,
    DeStn,
    DoRcn,
    EcRuc,
    EgTin,
    EsCif,
    EtTin,
    EuOssVat,
    GBVat,
    GeVat,
    GnNif,
    HkBr,
    HrOib,
    HuTin,
    IDNpwp,
    IlVat,
    InGst,
    IsVat,
    JpCn,
    JpRn,
    JpTrn,
    KePin,
    KgTin,
    KhTin,
    KrBrn,
    KzBin,
    LaTin,
    LiUid,
    LiVat,
    MaVat,
    MdVat,
    MePib,
    MkVat,
    MrNif,
    MxRfc,
    MyFrp,
    MyItn,
    MySst,
    NgTin,
    NoVat,
    NoVoec,
    NpPan,
    NzGst,
    OmVat,
    PeRuc,
    PhTin,
    RoTin,
    RsPib,
    RuInn,
    RuKpp,
    SaVat,
    SgGst,
    SgUen,
    SiTin,
    SnNinea,
    SrFin,
    SvNit,
    ThVat,
    TjTin,
    TrTin,
    TwVat,
    TzVat,
    UaVat,
    UgTin,
    UsEin,
    UyRuc,
    UzTin,
    UzVat,
    VeRif,
    VnTin,
    ZaVat,
    ZmTin,
    ZwTin,
}

sealed class TypeConverter : JsonConverter<Type>
{
    public override Type Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "ad_nrt" => CustomerTaxIDProperties.Type.AdNrt,
            "ae_trn" => CustomerTaxIDProperties.Type.AeTrn,
            "al_tin" => CustomerTaxIDProperties.Type.AlTin,
            "am_tin" => CustomerTaxIDProperties.Type.AmTin,
            "ao_tin" => CustomerTaxIDProperties.Type.AoTin,
            "ar_cuit" => CustomerTaxIDProperties.Type.ArCuit,
            "eu_vat" => CustomerTaxIDProperties.Type.EuVat,
            "au_abn" => CustomerTaxIDProperties.Type.AuAbn,
            "au_arn" => CustomerTaxIDProperties.Type.AuArn,
            "aw_tin" => CustomerTaxIDProperties.Type.AwTin,
            "az_tin" => CustomerTaxIDProperties.Type.AzTin,
            "ba_tin" => CustomerTaxIDProperties.Type.BaTin,
            "bb_tin" => CustomerTaxIDProperties.Type.BbTin,
            "bd_bin" => CustomerTaxIDProperties.Type.BdBin,
            "bf_ifu" => CustomerTaxIDProperties.Type.BfIfu,
            "bg_uic" => CustomerTaxIDProperties.Type.BgUic,
            "bh_vat" => CustomerTaxIDProperties.Type.BhVat,
            "bj_ifu" => CustomerTaxIDProperties.Type.BjIfu,
            "bo_tin" => CustomerTaxIDProperties.Type.BoTin,
            "br_cnpj" => CustomerTaxIDProperties.Type.BrCnpj,
            "br_cpf" => CustomerTaxIDProperties.Type.BrCpf,
            "bs_tin" => CustomerTaxIDProperties.Type.BsTin,
            "by_tin" => CustomerTaxIDProperties.Type.ByTin,
            "ca_bn" => CustomerTaxIDProperties.Type.CaBn,
            "ca_gst_hst" => CustomerTaxIDProperties.Type.CaGstHst,
            "ca_pst_bc" => CustomerTaxIDProperties.Type.CaPstBc,
            "ca_pst_mb" => CustomerTaxIDProperties.Type.CaPstMB,
            "ca_pst_sk" => CustomerTaxIDProperties.Type.CaPstSk,
            "ca_qst" => CustomerTaxIDProperties.Type.CaQst,
            "cd_nif" => CustomerTaxIDProperties.Type.CdNif,
            "ch_uid" => CustomerTaxIDProperties.Type.ChUid,
            "ch_vat" => CustomerTaxIDProperties.Type.ChVat,
            "cl_tin" => CustomerTaxIDProperties.Type.ClTin,
            "cm_niu" => CustomerTaxIDProperties.Type.CmNiu,
            "cn_tin" => CustomerTaxIDProperties.Type.CnTin,
            "co_nit" => CustomerTaxIDProperties.Type.CoNit,
            "cr_tin" => CustomerTaxIDProperties.Type.CrTin,
            "cv_nif" => CustomerTaxIDProperties.Type.CvNif,
            "de_stn" => CustomerTaxIDProperties.Type.DeStn,
            "do_rcn" => CustomerTaxIDProperties.Type.DoRcn,
            "ec_ruc" => CustomerTaxIDProperties.Type.EcRuc,
            "eg_tin" => CustomerTaxIDProperties.Type.EgTin,
            "es_cif" => CustomerTaxIDProperties.Type.EsCif,
            "et_tin" => CustomerTaxIDProperties.Type.EtTin,
            "eu_oss_vat" => CustomerTaxIDProperties.Type.EuOssVat,
            "gb_vat" => CustomerTaxIDProperties.Type.GBVat,
            "ge_vat" => CustomerTaxIDProperties.Type.GeVat,
            "gn_nif" => CustomerTaxIDProperties.Type.GnNif,
            "hk_br" => CustomerTaxIDProperties.Type.HkBr,
            "hr_oib" => CustomerTaxIDProperties.Type.HrOib,
            "hu_tin" => CustomerTaxIDProperties.Type.HuTin,
            "id_npwp" => CustomerTaxIDProperties.Type.IDNpwp,
            "il_vat" => CustomerTaxIDProperties.Type.IlVat,
            "in_gst" => CustomerTaxIDProperties.Type.InGst,
            "is_vat" => CustomerTaxIDProperties.Type.IsVat,
            "jp_cn" => CustomerTaxIDProperties.Type.JpCn,
            "jp_rn" => CustomerTaxIDProperties.Type.JpRn,
            "jp_trn" => CustomerTaxIDProperties.Type.JpTrn,
            "ke_pin" => CustomerTaxIDProperties.Type.KePin,
            "kg_tin" => CustomerTaxIDProperties.Type.KgTin,
            "kh_tin" => CustomerTaxIDProperties.Type.KhTin,
            "kr_brn" => CustomerTaxIDProperties.Type.KrBrn,
            "kz_bin" => CustomerTaxIDProperties.Type.KzBin,
            "la_tin" => CustomerTaxIDProperties.Type.LaTin,
            "li_uid" => CustomerTaxIDProperties.Type.LiUid,
            "li_vat" => CustomerTaxIDProperties.Type.LiVat,
            "ma_vat" => CustomerTaxIDProperties.Type.MaVat,
            "md_vat" => CustomerTaxIDProperties.Type.MdVat,
            "me_pib" => CustomerTaxIDProperties.Type.MePib,
            "mk_vat" => CustomerTaxIDProperties.Type.MkVat,
            "mr_nif" => CustomerTaxIDProperties.Type.MrNif,
            "mx_rfc" => CustomerTaxIDProperties.Type.MxRfc,
            "my_frp" => CustomerTaxIDProperties.Type.MyFrp,
            "my_itn" => CustomerTaxIDProperties.Type.MyItn,
            "my_sst" => CustomerTaxIDProperties.Type.MySst,
            "ng_tin" => CustomerTaxIDProperties.Type.NgTin,
            "no_vat" => CustomerTaxIDProperties.Type.NoVat,
            "no_voec" => CustomerTaxIDProperties.Type.NoVoec,
            "np_pan" => CustomerTaxIDProperties.Type.NpPan,
            "nz_gst" => CustomerTaxIDProperties.Type.NzGst,
            "om_vat" => CustomerTaxIDProperties.Type.OmVat,
            "pe_ruc" => CustomerTaxIDProperties.Type.PeRuc,
            "ph_tin" => CustomerTaxIDProperties.Type.PhTin,
            "ro_tin" => CustomerTaxIDProperties.Type.RoTin,
            "rs_pib" => CustomerTaxIDProperties.Type.RsPib,
            "ru_inn" => CustomerTaxIDProperties.Type.RuInn,
            "ru_kpp" => CustomerTaxIDProperties.Type.RuKpp,
            "sa_vat" => CustomerTaxIDProperties.Type.SaVat,
            "sg_gst" => CustomerTaxIDProperties.Type.SgGst,
            "sg_uen" => CustomerTaxIDProperties.Type.SgUen,
            "si_tin" => CustomerTaxIDProperties.Type.SiTin,
            "sn_ninea" => CustomerTaxIDProperties.Type.SnNinea,
            "sr_fin" => CustomerTaxIDProperties.Type.SrFin,
            "sv_nit" => CustomerTaxIDProperties.Type.SvNit,
            "th_vat" => CustomerTaxIDProperties.Type.ThVat,
            "tj_tin" => CustomerTaxIDProperties.Type.TjTin,
            "tr_tin" => CustomerTaxIDProperties.Type.TrTin,
            "tw_vat" => CustomerTaxIDProperties.Type.TwVat,
            "tz_vat" => CustomerTaxIDProperties.Type.TzVat,
            "ua_vat" => CustomerTaxIDProperties.Type.UaVat,
            "ug_tin" => CustomerTaxIDProperties.Type.UgTin,
            "us_ein" => CustomerTaxIDProperties.Type.UsEin,
            "uy_ruc" => CustomerTaxIDProperties.Type.UyRuc,
            "uz_tin" => CustomerTaxIDProperties.Type.UzTin,
            "uz_vat" => CustomerTaxIDProperties.Type.UzVat,
            "ve_rif" => CustomerTaxIDProperties.Type.VeRif,
            "vn_tin" => CustomerTaxIDProperties.Type.VnTin,
            "za_vat" => CustomerTaxIDProperties.Type.ZaVat,
            "zm_tin" => CustomerTaxIDProperties.Type.ZmTin,
            "zw_tin" => CustomerTaxIDProperties.Type.ZwTin,
            _ => (Type)(-1),
        };
    }

    public override void Write(Utf8JsonWriter writer, Type value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                CustomerTaxIDProperties.Type.AdNrt => "ad_nrt",
                CustomerTaxIDProperties.Type.AeTrn => "ae_trn",
                CustomerTaxIDProperties.Type.AlTin => "al_tin",
                CustomerTaxIDProperties.Type.AmTin => "am_tin",
                CustomerTaxIDProperties.Type.AoTin => "ao_tin",
                CustomerTaxIDProperties.Type.ArCuit => "ar_cuit",
                CustomerTaxIDProperties.Type.EuVat => "eu_vat",
                CustomerTaxIDProperties.Type.AuAbn => "au_abn",
                CustomerTaxIDProperties.Type.AuArn => "au_arn",
                CustomerTaxIDProperties.Type.AwTin => "aw_tin",
                CustomerTaxIDProperties.Type.AzTin => "az_tin",
                CustomerTaxIDProperties.Type.BaTin => "ba_tin",
                CustomerTaxIDProperties.Type.BbTin => "bb_tin",
                CustomerTaxIDProperties.Type.BdBin => "bd_bin",
                CustomerTaxIDProperties.Type.BfIfu => "bf_ifu",
                CustomerTaxIDProperties.Type.BgUic => "bg_uic",
                CustomerTaxIDProperties.Type.BhVat => "bh_vat",
                CustomerTaxIDProperties.Type.BjIfu => "bj_ifu",
                CustomerTaxIDProperties.Type.BoTin => "bo_tin",
                CustomerTaxIDProperties.Type.BrCnpj => "br_cnpj",
                CustomerTaxIDProperties.Type.BrCpf => "br_cpf",
                CustomerTaxIDProperties.Type.BsTin => "bs_tin",
                CustomerTaxIDProperties.Type.ByTin => "by_tin",
                CustomerTaxIDProperties.Type.CaBn => "ca_bn",
                CustomerTaxIDProperties.Type.CaGstHst => "ca_gst_hst",
                CustomerTaxIDProperties.Type.CaPstBc => "ca_pst_bc",
                CustomerTaxIDProperties.Type.CaPstMB => "ca_pst_mb",
                CustomerTaxIDProperties.Type.CaPstSk => "ca_pst_sk",
                CustomerTaxIDProperties.Type.CaQst => "ca_qst",
                CustomerTaxIDProperties.Type.CdNif => "cd_nif",
                CustomerTaxIDProperties.Type.ChUid => "ch_uid",
                CustomerTaxIDProperties.Type.ChVat => "ch_vat",
                CustomerTaxIDProperties.Type.ClTin => "cl_tin",
                CustomerTaxIDProperties.Type.CmNiu => "cm_niu",
                CustomerTaxIDProperties.Type.CnTin => "cn_tin",
                CustomerTaxIDProperties.Type.CoNit => "co_nit",
                CustomerTaxIDProperties.Type.CrTin => "cr_tin",
                CustomerTaxIDProperties.Type.CvNif => "cv_nif",
                CustomerTaxIDProperties.Type.DeStn => "de_stn",
                CustomerTaxIDProperties.Type.DoRcn => "do_rcn",
                CustomerTaxIDProperties.Type.EcRuc => "ec_ruc",
                CustomerTaxIDProperties.Type.EgTin => "eg_tin",
                CustomerTaxIDProperties.Type.EsCif => "es_cif",
                CustomerTaxIDProperties.Type.EtTin => "et_tin",
                CustomerTaxIDProperties.Type.EuOssVat => "eu_oss_vat",
                CustomerTaxIDProperties.Type.GBVat => "gb_vat",
                CustomerTaxIDProperties.Type.GeVat => "ge_vat",
                CustomerTaxIDProperties.Type.GnNif => "gn_nif",
                CustomerTaxIDProperties.Type.HkBr => "hk_br",
                CustomerTaxIDProperties.Type.HrOib => "hr_oib",
                CustomerTaxIDProperties.Type.HuTin => "hu_tin",
                CustomerTaxIDProperties.Type.IDNpwp => "id_npwp",
                CustomerTaxIDProperties.Type.IlVat => "il_vat",
                CustomerTaxIDProperties.Type.InGst => "in_gst",
                CustomerTaxIDProperties.Type.IsVat => "is_vat",
                CustomerTaxIDProperties.Type.JpCn => "jp_cn",
                CustomerTaxIDProperties.Type.JpRn => "jp_rn",
                CustomerTaxIDProperties.Type.JpTrn => "jp_trn",
                CustomerTaxIDProperties.Type.KePin => "ke_pin",
                CustomerTaxIDProperties.Type.KgTin => "kg_tin",
                CustomerTaxIDProperties.Type.KhTin => "kh_tin",
                CustomerTaxIDProperties.Type.KrBrn => "kr_brn",
                CustomerTaxIDProperties.Type.KzBin => "kz_bin",
                CustomerTaxIDProperties.Type.LaTin => "la_tin",
                CustomerTaxIDProperties.Type.LiUid => "li_uid",
                CustomerTaxIDProperties.Type.LiVat => "li_vat",
                CustomerTaxIDProperties.Type.MaVat => "ma_vat",
                CustomerTaxIDProperties.Type.MdVat => "md_vat",
                CustomerTaxIDProperties.Type.MePib => "me_pib",
                CustomerTaxIDProperties.Type.MkVat => "mk_vat",
                CustomerTaxIDProperties.Type.MrNif => "mr_nif",
                CustomerTaxIDProperties.Type.MxRfc => "mx_rfc",
                CustomerTaxIDProperties.Type.MyFrp => "my_frp",
                CustomerTaxIDProperties.Type.MyItn => "my_itn",
                CustomerTaxIDProperties.Type.MySst => "my_sst",
                CustomerTaxIDProperties.Type.NgTin => "ng_tin",
                CustomerTaxIDProperties.Type.NoVat => "no_vat",
                CustomerTaxIDProperties.Type.NoVoec => "no_voec",
                CustomerTaxIDProperties.Type.NpPan => "np_pan",
                CustomerTaxIDProperties.Type.NzGst => "nz_gst",
                CustomerTaxIDProperties.Type.OmVat => "om_vat",
                CustomerTaxIDProperties.Type.PeRuc => "pe_ruc",
                CustomerTaxIDProperties.Type.PhTin => "ph_tin",
                CustomerTaxIDProperties.Type.RoTin => "ro_tin",
                CustomerTaxIDProperties.Type.RsPib => "rs_pib",
                CustomerTaxIDProperties.Type.RuInn => "ru_inn",
                CustomerTaxIDProperties.Type.RuKpp => "ru_kpp",
                CustomerTaxIDProperties.Type.SaVat => "sa_vat",
                CustomerTaxIDProperties.Type.SgGst => "sg_gst",
                CustomerTaxIDProperties.Type.SgUen => "sg_uen",
                CustomerTaxIDProperties.Type.SiTin => "si_tin",
                CustomerTaxIDProperties.Type.SnNinea => "sn_ninea",
                CustomerTaxIDProperties.Type.SrFin => "sr_fin",
                CustomerTaxIDProperties.Type.SvNit => "sv_nit",
                CustomerTaxIDProperties.Type.ThVat => "th_vat",
                CustomerTaxIDProperties.Type.TjTin => "tj_tin",
                CustomerTaxIDProperties.Type.TrTin => "tr_tin",
                CustomerTaxIDProperties.Type.TwVat => "tw_vat",
                CustomerTaxIDProperties.Type.TzVat => "tz_vat",
                CustomerTaxIDProperties.Type.UaVat => "ua_vat",
                CustomerTaxIDProperties.Type.UgTin => "ug_tin",
                CustomerTaxIDProperties.Type.UsEin => "us_ein",
                CustomerTaxIDProperties.Type.UyRuc => "uy_ruc",
                CustomerTaxIDProperties.Type.UzTin => "uz_tin",
                CustomerTaxIDProperties.Type.UzVat => "uz_vat",
                CustomerTaxIDProperties.Type.VeRif => "ve_rif",
                CustomerTaxIDProperties.Type.VnTin => "vn_tin",
                CustomerTaxIDProperties.Type.ZaVat => "za_vat",
                CustomerTaxIDProperties.Type.ZmTin => "zm_tin",
                CustomerTaxIDProperties.Type.ZwTin => "zw_tin",
                _ => throw new System::ArgumentOutOfRangeException(nameof(value)),
            },
            options
        );
    }
}
