using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Orb.Models.Events.EventIngestParamsProperties;

[JsonConverter(typeof(ModelConverter<Event>))]
public sealed record class Event : ModelBase, IFromRaw<Event>
{
    /// <summary>
    /// A name to meaningfully identify the action or event type.
    /// </summary>
    public required string EventName
    {
        get
        {
            if (!this.Properties.TryGetValue("event_name", out JsonElement element))
                throw new ArgumentOutOfRangeException("event_name", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("event_name");
        }
        set { this.Properties["event_name"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// A unique value, generated by the client, that is used to de-duplicate events.
    /// Exactly one event with a given idempotency key will be ingested, which allows
    /// for safe request retries.
    /// </summary>
    public required string IdempotencyKey
    {
        get
        {
            if (!this.Properties.TryGetValue("idempotency_key", out JsonElement element))
                throw new ArgumentOutOfRangeException(
                    "idempotency_key",
                    "Missing required argument"
                );

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("idempotency_key");
        }
        set { this.Properties["idempotency_key"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// A dictionary of custom properties. Values in this dictionary must be numeric,
    /// boolean, or strings. Nested dictionaries are disallowed.
    /// </summary>
    public required Dictionary<string, JsonElement> Properties1
    {
        get
        {
            if (!this.Properties.TryGetValue("properties", out JsonElement element))
                throw new ArgumentOutOfRangeException("properties", "Missing required argument");

            return JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(
                    element,
                    ModelBase.SerializerOptions
                ) ?? throw new ArgumentNullException("properties");
        }
        set { this.Properties["properties"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent
    /// the time that usage was recorded, and is particularly important to attribute
    /// usage to a given billing period.
    /// </summary>
    public required DateTime Timestamp
    {
        get
        {
            if (!this.Properties.TryGetValue("timestamp", out JsonElement element))
                throw new ArgumentOutOfRangeException("timestamp", "Missing required argument");

            return JsonSerializer.Deserialize<DateTime>(element, ModelBase.SerializerOptions);
        }
        set { this.Properties["timestamp"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The Orb Customer identifier
    /// </summary>
    public string? CustomerID
    {
        get
        {
            if (!this.Properties.TryGetValue("customer_id", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element, ModelBase.SerializerOptions);
        }
        set { this.Properties["customer_id"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// An alias for the Orb customer, whose mapping is specified when creating the customer
    /// </summary>
    public string? ExternalCustomerID
    {
        get
        {
            if (!this.Properties.TryGetValue("external_customer_id", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element, ModelBase.SerializerOptions);
        }
        set { this.Properties["external_customer_id"] = JsonSerializer.SerializeToElement(value); }
    }

    public override void Validate()
    {
        _ = this.EventName;
        _ = this.IdempotencyKey;
        foreach (var item in this.Properties1.Values)
        {
            _ = item;
        }
        _ = this.Timestamp;
        _ = this.CustomerID;
        _ = this.ExternalCustomerID;
    }

    public Event() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Event(Dictionary<string, JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static Event FromRawUnchecked(Dictionary<string, JsonElement> properties)
    {
        return new(properties);
    }
}
