using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using PlanCreateParamsProperties = Orb.Models.Plans.PlanCreateParamsProperties;

namespace Orb.Models.Plans;

/// <summary>
/// This endpoint allows creation of plans including their prices.
/// </summary>
public sealed record class PlanCreateParams : ParamsBase
{
    public Dictionary<string, JsonElement> BodyProperties { get; set; } = [];

    /// <summary>
    /// An ISO 4217 currency string for invoices generated by subscriptions on this plan.
    /// </summary>
    public required string Currency
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("currency", out JsonElement element))
                throw new ArgumentOutOfRangeException("currency", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("currency");
        }
        set { this.BodyProperties["currency"] = JsonSerializer.SerializeToElement(value); }
    }

    public required string Name
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("name", out JsonElement element))
                throw new ArgumentOutOfRangeException("name", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element)
                ?? throw new ArgumentNullException("name");
        }
        set { this.BodyProperties["name"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Prices for this plan. If the plan has phases, this includes prices across all
    /// phases of the plan.
    /// </summary>
    public required List<PlanCreateParamsProperties::Price1> Prices
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("prices", out JsonElement element))
                throw new ArgumentOutOfRangeException("prices", "Missing required argument");

            return JsonSerializer.Deserialize<List<PlanCreateParamsProperties::Price1>>(element)
                ?? throw new ArgumentNullException("prices");
        }
        set { this.BodyProperties["prices"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Adjustments for this plan. If the plan has phases, this includes adjustments
    /// across all phases of the plan.
    /// </summary>
    public List<PlanCreateParamsProperties::Adjustment>? Adjustments
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("adjustments", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<List<PlanCreateParamsProperties::Adjustment>?>(
                element
            );
        }
        set { this.BodyProperties["adjustments"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Free-form text which is available on the invoice PDF and the Orb invoice portal.
    /// </summary>
    public string? DefaultInvoiceMemo
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("default_invoice_memo", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element);
        }
        set
        {
            this.BodyProperties["default_invoice_memo"] = JsonSerializer.SerializeToElement(value);
        }
    }

    public string? ExternalPlanID
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("external_plan_id", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element);
        }
        set { this.BodyProperties["external_plan_id"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// User-specified key/value pairs for the resource. Individual keys can be removed
    /// by setting the value to `null`, and the entire metadata mapping can be cleared
    /// by setting `metadata` to `null`.
    /// </summary>
    public Dictionary<string, string?>? Metadata
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("metadata", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<Dictionary<string, string?>?>(element);
        }
        set { this.BodyProperties["metadata"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The net terms determines the difference between the invoice date and the issue
    /// date for the invoice. If you intend the invoice to be due on issue, set this
    /// to 0.
    /// </summary>
    public long? NetTerms
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("net_terms", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<long?>(element);
        }
        set { this.BodyProperties["net_terms"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Configuration of pre-defined phases, each with their own prices and adjustments.
    /// Leave unspecified for plans with a single phase.
    /// </summary>
    public List<PlanCreateParamsProperties::PlanPhase>? PlanPhases
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("plan_phases", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<List<PlanCreateParamsProperties::PlanPhase>?>(
                element
            );
        }
        set { this.BodyProperties["plan_phases"] = JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The status of the plan to create (either active or draft). If not specified,
    /// this defaults to active.
    /// </summary>
    public PlanCreateParamsProperties::Status? Status
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("status", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<PlanCreateParamsProperties::Status?>(element);
        }
        set { this.BodyProperties["status"] = JsonSerializer.SerializeToElement(value); }
    }

    public override Uri Url(IOrbClient client)
    {
        return new UriBuilder(client.BaseUrl.ToString().TrimEnd('/') + "/plans")
        {
            Query = this.QueryString(client),
        }.Uri;
    }

    public StringContent BodyContent()
    {
        return new(
            JsonSerializer.Serialize(this.BodyProperties),
            Encoding.UTF8,
            "application/json"
        );
    }

    public void AddHeadersToRequest(HttpRequestMessage request, IOrbClient client)
    {
        ParamsBase.AddDefaultHeaders(request, client);
        foreach (var item in this.HeaderProperties)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }
}
