using Generic = System.Collections.Generic;
using Http = System.Net.Http;
using Json = System.Text.Json;
using Orb = Orb;
using PlanCreateParamsProperties = Orb.Models.Plans.PlanCreateParamsProperties;
using System = System;
using Text = System.Text;

namespace Orb.Models.Plans;

/// <summary>
/// This endpoint allows creation of plans including their prices.
/// </summary>
public sealed record class PlanCreateParams : Orb::ParamsBase
{
    public Generic::Dictionary<string, Json::JsonElement> BodyProperties { get; set; } = [];

    /// <summary>
    /// An ISO 4217 currency string for invoices generated by subscriptions on this plan.
    /// </summary>
    public required string Currency
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("currency", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "currency",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("currency");
        }
        set { this.BodyProperties["currency"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    public required string Name
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("name", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("name", "Missing required argument");

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("name");
        }
        set { this.BodyProperties["name"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Prices for this plan. If the plan has phases, this includes prices across all
    /// phases of the plan.
    /// </summary>
    public required Generic::List<PlanCreateParamsProperties::Price> Prices
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("prices", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "prices",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<Generic::List<PlanCreateParamsProperties::Price>>(
                    element
                ) ?? throw new System::ArgumentNullException("prices");
        }
        set { this.BodyProperties["prices"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Adjustments for this plan. If the plan has phases, this includes adjustments
    /// across all phases of the plan.
    /// </summary>
    public Generic::List<PlanCreateParamsProperties::Adjustment>? Adjustments
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("adjustments", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<Generic::List<PlanCreateParamsProperties::Adjustment>?>(
                element
            );
        }
        set { this.BodyProperties["adjustments"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Free-form text which is available on the invoice PDF and the Orb invoice portal.
    /// </summary>
    public string? DefaultInvoiceMemo
    {
        get
        {
            if (
                !this.BodyProperties.TryGetValue(
                    "default_invoice_memo",
                    out Json::JsonElement element
                )
            )
                return null;

            return Json::JsonSerializer.Deserialize<string?>(element);
        }
        set
        {
            this.BodyProperties["default_invoice_memo"] = Json::JsonSerializer.SerializeToElement(
                value
            );
        }
    }

    public string? ExternalPlanID
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("external_plan_id", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<string?>(element);
        }
        set
        {
            this.BodyProperties["external_plan_id"] = Json::JsonSerializer.SerializeToElement(
                value
            );
        }
    }

    /// <summary>
    /// User-specified key/value pairs for the resource. Individual keys can be removed
    /// by setting the value to `null`, and the entire metadata mapping can be cleared
    /// by setting `metadata` to `null`.
    /// </summary>
    public Generic::Dictionary<string, string?>? Metadata
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("metadata", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<Generic::Dictionary<string, string?>?>(element);
        }
        set { this.BodyProperties["metadata"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The net terms determines the difference between the invoice date and the issue
    /// date for the invoice. If you intend the invoice to be due on issue, set this
    /// to 0.
    /// </summary>
    public long? NetTerms
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("net_terms", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<long?>(element);
        }
        set { this.BodyProperties["net_terms"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// Configuration of pre-defined phases, each with their own prices and adjustments.
    /// Leave unspecified for plans with a single phase.
    /// </summary>
    public Generic::List<PlanCreateParamsProperties::PlanPhase>? PlanPhases
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("plan_phases", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<Generic::List<PlanCreateParamsProperties::PlanPhase>?>(
                element
            );
        }
        set { this.BodyProperties["plan_phases"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The status of the plan to create (either active or draft). If not specified,
    /// this defaults to active.
    /// </summary>
    public PlanCreateParamsProperties::Status? Status
    {
        get
        {
            if (!this.BodyProperties.TryGetValue("status", out Json::JsonElement element))
                return null;

            return Json::JsonSerializer.Deserialize<PlanCreateParamsProperties::Status?>(element);
        }
        set { this.BodyProperties["status"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    public override System::Uri Url(Orb::IOrbClient client)
    {
        return new System::UriBuilder(client.BaseUrl.ToString().TrimEnd('/') + "/plans")
        {
            Query = this.QueryString(client),
        }.Uri;
    }

    public Http::StringContent BodyContent()
    {
        return new Http::StringContent(
            Json::JsonSerializer.Serialize(this.BodyProperties),
            Text::Encoding.UTF8,
            "application/json"
        );
    }

    public void AddHeadersToRequest(Http::HttpRequestMessage request, Orb::IOrbClient client)
    {
        Orb::ParamsBase.AddDefaultHeaders(request, client);
        foreach (var item in this.HeaderProperties)
        {
            Orb::ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }
}
