using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Orb.Core;

namespace Orb.Models.Events;

[JsonConverter(typeof(ModelConverter<EventSearchResponse, EventSearchResponseFromRaw>))]
public sealed record class EventSearchResponse : ModelBase
{
    public required IReadOnlyList<Data> Data
    {
        get { return ModelBase.GetNotNullClass<List<Data>>(this.RawData, "data"); }
        init { ModelBase.Set(this._rawData, "data", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        foreach (var item in this.Data)
        {
            item.Validate();
        }
    }

    public EventSearchResponse() { }

    public EventSearchResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    EventSearchResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="EventSearchResponseFromRaw.FromRawUnchecked"/>
    public static EventSearchResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public EventSearchResponse(List<Data> data)
        : this()
    {
        this.Data = data;
    }
}

class EventSearchResponseFromRaw : IFromRaw<EventSearchResponse>
{
    /// <inheritdoc/>
    public EventSearchResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        EventSearchResponse.FromRawUnchecked(rawData);
}

/// <summary>
/// The [Event](/core-concepts#event) resource represents a usage event that has been
/// created for a customer. Events are the core of Orb's usage-based billing model,
/// and are used to calculate the usage charges for a given billing period.
/// </summary>
[JsonConverter(typeof(ModelConverter<Data, DataFromRaw>))]
public sealed record class Data : ModelBase
{
    /// <summary>
    /// A unique value, generated by the client, that is used to de-duplicate events.
    /// Exactly one event with a given idempotency key will be ingested, which allows
    /// for safe request retries.
    /// </summary>
    public required string ID
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "id"); }
        init { ModelBase.Set(this._rawData, "id", value); }
    }

    /// <summary>
    /// The Orb Customer identifier
    /// </summary>
    public required string? CustomerID
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "customer_id"); }
        init { ModelBase.Set(this._rawData, "customer_id", value); }
    }

    /// <summary>
    /// A boolean indicating whether the event is currently deprecated.
    /// </summary>
    public required bool Deprecated
    {
        get { return ModelBase.GetNotNullStruct<bool>(this.RawData, "deprecated"); }
        init { ModelBase.Set(this._rawData, "deprecated", value); }
    }

    /// <summary>
    /// A name to meaningfully identify the action or event type.
    /// </summary>
    public required string EventName
    {
        get { return ModelBase.GetNotNullClass<string>(this.RawData, "event_name"); }
        init { ModelBase.Set(this._rawData, "event_name", value); }
    }

    /// <summary>
    /// An alias for the Orb customer, whose mapping is specified when creating the customer
    /// </summary>
    public required string? ExternalCustomerID
    {
        get { return ModelBase.GetNullableClass<string>(this.RawData, "external_customer_id"); }
        init { ModelBase.Set(this._rawData, "external_customer_id", value); }
    }

    /// <summary>
    /// A dictionary of custom properties. Values in this dictionary must be numeric,
    /// boolean, or strings. Nested dictionaries are disallowed.
    /// </summary>
    public required IReadOnlyDictionary<string, JsonElement> Properties
    {
        get
        {
            return ModelBase.GetNotNullClass<Dictionary<string, JsonElement>>(
                this.RawData,
                "properties"
            );
        }
        init { ModelBase.Set(this._rawData, "properties", value); }
    }

    /// <summary>
    /// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent
    /// the time that usage was recorded, and is particularly important to attribute
    /// usage to a given billing period.
    /// </summary>
    public required DateTimeOffset Timestamp
    {
        get { return ModelBase.GetNotNullStruct<DateTimeOffset>(this.RawData, "timestamp"); }
        init { ModelBase.Set(this._rawData, "timestamp", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.CustomerID;
        _ = this.Deprecated;
        _ = this.EventName;
        _ = this.ExternalCustomerID;
        _ = this.Properties;
        _ = this.Timestamp;
    }

    public Data() { }

    public Data(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    Data(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = [.. rawData];
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="DataFromRaw.FromRawUnchecked"/>
    public static Data FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class DataFromRaw : IFromRaw<Data>
{
    /// <inheritdoc/>
    public Data FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        Data.FromRawUnchecked(rawData);
}
