using CodeAnalysis = System.Diagnostics.CodeAnalysis;
using Generic = System.Collections.Generic;
using Json = System.Text.Json;
using Orb = Orb;
using Serialization = System.Text.Json.Serialization;
using System = System;

namespace Orb.Models.Events.EventSearchResponseProperties;

/// <summary>
/// The [Event](/core-concepts#event) resource represents a usage event that has
/// been created for a customer. Events are the core of Orb's usage-based billing
/// model, and are used to calculate the usage charges for a given billing period.
/// </summary>
[Serialization::JsonConverter(typeof(Orb::ModelConverter<Data>))]
public sealed record class Data : Orb::ModelBase, Orb::IFromRaw<Data>
{
    /// <summary>
    /// A unique value, generated by the client, that is used to de-duplicate events.
    /// Exactly one event with a given idempotency key will be ingested, which allows
    /// for safe request retries.
    /// </summary>
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException("id", "Missing required argument");

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("id");
        }
        set { this.Properties["id"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// The Orb Customer identifier
    /// </summary>
    public required string? CustomerID
    {
        get
        {
            if (!this.Properties.TryGetValue("customer_id", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "customer_id",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string?>(element);
        }
        set { this.Properties["customer_id"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// A boolean indicating whether the event is currently deprecated.
    /// </summary>
    public required bool Deprecated
    {
        get
        {
            if (!this.Properties.TryGetValue("deprecated", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "deprecated",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<bool>(element);
        }
        set { this.Properties["deprecated"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// A name to meaningfully identify the action or event type.
    /// </summary>
    public required string EventName
    {
        get
        {
            if (!this.Properties.TryGetValue("event_name", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "event_name",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string>(element)
                ?? throw new System::ArgumentNullException("event_name");
        }
        set { this.Properties["event_name"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// An alias for the Orb customer, whose mapping is specified when creating the customer
    /// </summary>
    public required string? ExternalCustomerID
    {
        get
        {
            if (!this.Properties.TryGetValue("external_customer_id", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "external_customer_id",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<string?>(element);
        }
        set
        {
            this.Properties["external_customer_id"] = Json::JsonSerializer.SerializeToElement(
                value
            );
        }
    }

    /// <summary>
    /// A dictionary of custom properties. Values in this dictionary must be numeric,
    /// boolean, or strings. Nested dictionaries are disallowed.
    /// </summary>
    public required Generic::Dictionary<string, Json::JsonElement> Properties1
    {
        get
        {
            if (!this.Properties.TryGetValue("properties", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "properties",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<Generic::Dictionary<string, Json::JsonElement>>(
                    element
                ) ?? throw new System::ArgumentNullException("properties");
        }
        set { this.Properties["properties"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    /// <summary>
    /// An ISO 8601 format date with no timezone offset (i.e. UTC). This should represent
    /// the time that usage was recorded, and is particularly important to attribute
    /// usage to a given billing period.
    /// </summary>
    public required System::DateTime Timestamp
    {
        get
        {
            if (!this.Properties.TryGetValue("timestamp", out Json::JsonElement element))
                throw new System::ArgumentOutOfRangeException(
                    "timestamp",
                    "Missing required argument"
                );

            return Json::JsonSerializer.Deserialize<System::DateTime>(element);
        }
        set { this.Properties["timestamp"] = Json::JsonSerializer.SerializeToElement(value); }
    }

    public override void Validate()
    {
        _ = this.ID;
        _ = this.CustomerID;
        _ = this.Deprecated;
        _ = this.EventName;
        _ = this.ExternalCustomerID;
        foreach (var item in this.Properties1.Values)
        {
            _ = item;
        }
        _ = this.Timestamp;
    }

    public Data() { }

#pragma warning disable CS8618
    [CodeAnalysis::SetsRequiredMembers]
    Data(Generic::Dictionary<string, Json::JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static Data FromRawUnchecked(Generic::Dictionary<string, Json::JsonElement> properties)
    {
        return new(properties);
    }
}
